version: '3.7'
services:
  api:
    build:
      context: ./api
      dockerfile: .docker/Dockerfile
    restart: always
    ports:
      - 8000:80
  front-end:
    build:
      context: ./front-end
    restart: always
    ports:
      - 8080:8080
